# Generated by Django 5.2.14 on 2026-07-14 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="socialaccount",
            old_name="created_at",
            new_name="connected_at",
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="page_access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="page_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="page_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="account_id",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="is_connected",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name="socialaccount",
            unique_together={("user", "platform")},
        ),
    ]
