# Generated by Django 5.2.14 on 2026-07-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "social_accounts",
            "0002_rename_created_at_socialaccount_connected_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialaccount",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("linkedin", "LinkedIn"),
                    ("twitter", "X (Twitter)"),
                    ("pinterest", "Pinterest"),
                    ("threads", "Threads"),
                ],
                max_length=20,
            ),
        ),
    ]
