# Generated by Django 5.2.14 on 2026-07-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        ("social_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="social_accounts",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="social_accounts.socialaccount"
            ),
        ),
    ]
