# Generated by Django 5.2.14 on 2026-07-07 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_social_accounts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="caption",
        ),
        migrations.RemoveField(
            model_name="post",
            name="social_accounts",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="posts/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="scheduled_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("posted", "Posted"),
                    ("failed", "Failed"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
