# Generated by Django 5.2.14 on 2026-07-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_make_post_image_optional_and_default_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="platforms",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
