# Generated by Django 5.2.14 on 2026-07-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_add_title_to_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="caption",
            field=models.TextField(blank=True),
        ),
    ]
