# Generated by Django 5.2.14 on 2026-07-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_alter_post_caption"),
        ("social_accounts", "0003_alter_socialaccount_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="social_accounts",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="social_accounts.socialaccount"
            ),
        ),
    ]
